### ISSUE TITLE
problem with spotify logo

### ISSUE THREAD

**Issue by Caeliiaa** [M7S/dockbarx#151]
Hello

I have mxlinux with xfce, and I have installed the xfce4-dockbarx-plugin, I have configured it and everything worked correctly, but then I have run spotify, and it does not show correctly, it shows a default icon, it looks like this:

https://imgur.com/Oj8ZGta.png

is there any way to fix this?

**Comment by xuzhen** [comment]
fixed in https://github.com/xuzhen/dockbarx/commit/56933975e108d7afc66ca48b6f45464bdbedb2d5

**Comment by Caeliiaa** [comment]
Is it necessary to update? I have also updated packages and it remains the same: u

**Comment by xuzhen** [comment]
Only the packages in [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx) were updated currently. You can download and install [the package](http://ppa.launchpad.net/xuzhen666/dockbarx/ubuntu/pool/main/d/dockbarx/dockbarx-common_1.0~beta+git20201018-1~ppa1_all.deb).

**Comment by Caeliiaa** [comment]
hi, I have already updated the packages to the latest version found in your PPA. But the problem is still present.

see the image:
https://imgur.com/hfzZu5t.png

the center dock is the dockbarx opened with dockx (I placed it there so that the difference could be seen) and the rest is the mxlinux xfce panel.
see how with the  xfce4-dockbarx-plugin, the spotify app has a standard icon, while with dockx it is displayed correctly.

**Comment by xuzhen** [comment]
Try the new version (1.0\~beta+git20210212-1\~ppa1) in my PPA. It contains a patch for https://github.com/M7S/dockbarx/issues/164, and may fix your problem as well.
